# Generated by Django 2.2.5 on 2019-09-11 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('electronic', 'Electronic'), ('stationary', 'Stationary'), ('roomdecor', 'Room Decor'), ('vehicle', 'Vehicle'), ('job', 'Job'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('college', models.CharField(blank=True, max_length=30, null=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
