# Generated by Django 2.2.5 on 2019-09-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tools_and_instruments', 'Tools and Instruments'), ('seeds', 'Seeds'), ('fertilizers', 'Fertilizers'), ('farm_machinery', 'Farm Machinery'), ('job', 'Job'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
